name: CI

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Copy config
        run: cp ./src/main/resources/application_example.yml ./src/main/resources/application.yml
      - name: Run lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Copy config
        run: cp ./src/main/resources/application_example.yml ./src/main/resources/application.yml
      - name: Run build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test
